// <auto-generated />
namespace NivelAccesDate_CF_ORM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class quickfix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(quickfix));
        
        string IMigrationMetadata.Id
        {
            get { return "202401210752554_quickfix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
